### ISSUE TITLE
Research Spike: Investigate how to launch a notebook in SMCE with in-region access for running code

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-documentation#10]
Acceptance Criteria:
- [ ] A document outlining the options and proposing a solution (complete https://docs.google.com/document/d/12JVgZZRqDUpoH89vcLYJn2LMgXks_LQcF7ZUL-fBdH0/edit#)

Requirements
- An anonymous user can run code in https://nasa-impact.github.io/veda-documentation/ via a cloud-hosted notebook
- Cloud-hosted notebook is in SMCE us-west-2
- Notebook can access data
- Users launch "fresh" instances of the notebook so that if another user changes the code or changes are made in this repo, they should not appear in newly launched instances of the notebook.

**Comment by abarciauskas-bgse** [comment]
As background, I started running notebooks via notebooks in Sagemaker https://us-west-2.console.aws.amazon.com/sagemaker/home?region=us-west-2#/notebook-instances/stac-api-example-notebooks using the role `vedaDataAccess`. We want to do something similar but in the SMCE AWS account and with a role dedicated to this purpose.

Additional tasks:
- [ ] Meet with Ramon and get their advice on the deployment strategy with Ramon / SMCE team (should it be with sagemaker or some deployment for jupyternotebooks they already use)
- [ ] Determine how the deployment will have permission to access the data, will it be through a role or through us-west-2 blanket access
- [ ] Figure out how to integrate the example notebooks so that they can run "on-launch"
- [ ] Add links for users to launch or open the notebooks to the dashboard

**Comment by abarciauskas-bgse** [comment]
Started a document here: https://docs.google.com/document/d/12JVgZZRqDUpoH89vcLYJn2LMgXks_LQcF7ZUL-fBdH0/edit#heading=h.qlgieh3fjq3h

**Comment by tgirgin23** [comment]
Is this something that we can start working on? Since the requirement is an anonymous user can run code from a notebook, do we want to use something else than Che (I believe we discussed using Binder or citizen scientists and anonymous users?)

**Comment by tracetechnical** [comment]
@tgirgin23 I think this is dependent on us submitting the documents to get access to SMCE.
