### ISSUE TITLE
Update API URLs

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-documentation#12]
The `.xyz` endpoints for the delta-backend STAC and Raster APIs are deprecated and references should be updated to the new `.com` domains. The NASA VPN currently blocks the `.xyz` versions. 

**AC**
`*delta-backend.xyz` URL references updated to `*delta-backend.com` in documentation and example notebooks.

**Comment by abarciauskas-bgse** [comment]
Updated the docs. I have been too loose in pushing to main though so I will protect that branch from push w/o PR merge.

@anayeaye can you check my work in https://nasa-impact.github.io/veda-documentation/

**Comment by anayeaye** [comment]
@abarciauskas-bgse There are a couple `/` that might be a problem? In these two notebooks:
https://nasa-impact.github.io/veda-documentation/timeseries-rioxarray-stackstac.html
https://nasa-impact.github.io/veda-documentation/open-and-plot.html

That's all I see and I'm not sure if it's a problem. It all looks good to me.

**Comment by abarciauskas-bgse** [comment]
@anayeaye I tested the notebooks again locally and they ran ok - was there a specific place you were concerned about the `/` being problematic?

**Comment by anayeaye** [comment]
@abarciauskas-bgse Nope, that was just the only thing I saw that could possibly be an issue--I had not tried running the notebooks, sounds like things are good.
