### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by jsignell** [NASA-IMPACT/veda-documentation#32]
I was trying to reconcile the differences between this repo and https://github.com/NASA-IMPACT/veda-docs. It seems like veda-docs is the newer version. If that is the case I think it would be beneficial to:
- add a note to the README in this repo (and to the gh-pages rendered site)
- archive this repo

**Comment by abarciauskas-bgse** [comment]
I can't close this ticket when the repo is archived so closing and then archiving ...
